// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type CarInput struct {
	Model string             `json:"model"`
	Owner primitive.ObjectID `json:"owner"`
}

type Mutation struct {
}

type PersonInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type Query struct {
}
