// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID    string  `json:"id"`
	Model string  `json:"model"`
	Owner *Person `json:"owner"`
}

type CarInput struct {
	Model string `json:"model"`
	Owner string `json:"owner"`
}

type Mutation struct {
}

type Person struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type PersonInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type Query struct {
}
